<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AccountRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccountRepository extends EntityRepository
{
    public function findAllAccounts($id)
    {
        $em = $this->getEntityManager();
        $dql = $em->createQueryBuilder();
        $dql->select( 'a.id','a.status', 'a.checkin', 'b.id as mesaid', 'b.name as mesa')
            ->from('AppBundle:Account', 'a')
            ->innerJoin('a.barTable', 'b')
            ->where('a.user = :id')
            ->orderBy('a.id','desc');

        $dql->setParameter('id', $id);

        return $dql->getQuery()->getResult();
    }

    public function findAccountByUserIdAndTableId($accountId, $userId)
    {
        $em = $this->getEntityManager();
        $dql = $em->createQueryBuilder();
        $dql->select('a')
            ->from('AppBundle:Account', 'a')
            ->where('a.id = :accountId')
            ->andWhere('a.user = :userId');

        $dql->setParameter('accountId', $accountId);
        $dql->setParameter('userId', $userId);;

        return $dql->getQuery()->getSingleResult();
    }
}
