<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AccountRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccountRepository extends EntityRepository
{
    public function findAllAccounts($id)
    {
        $em = $this->getEntityManager();
        $dql = $em->createQueryBuilder();
        $dql->select( 'a.id','a.status', 'b.name as mesa')
            ->from('AppBundle:Account', 'a')
            ->innerJoin('a.barTable', 'b')
            ->where('a.user = :id');

        $dql->setParameter('id', $id);

        return $dql->getQuery()->getResult();
    }

    public function findAccountByUserIdAndTableId($userId, $tableId)
    {
        $em = $this->getEntityManager();
        $dql = $em->createQueryBuilder();
        $dql->select('a')
            ->from('AppBundle:Account', 'a')
            ->where('a.user = :userId')
            ->andWhere('a.barTable = :tableId');

        $dql->setParameter('userId', $userId);
        $dql->setParameter('tableId', $tableId);

        return $dql->getQuery()->getSingleResult();
    }
}
