<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BarTableRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BarTableRepository extends EntityRepository
{
    public function findTablesByWaiter($id)
    {
        $em = $this->getEntityManager();
        $dql = $em->createQueryBuilder();
        $dql->select( 't.id', 't.name')
            ->from('AppBundle:User', 'u')
            ->join('u.barTables', 't')
            ->where('u.id = :id');

        $dql->setParameter('id', $id);

        return $dql->getQuery()->getResult();
    }
}
