<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * NoteProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NoteProductRepository extends EntityRepository
{
    public function findSalesByCategoryProductAndWaiter($t)
    {
        $em = $this->getEntityManager();
        $dql = $em->createQueryBuilder();
        $dql->select('concat(u.name, \' \', u.firstLastName) as waiter', 'c.name as category', 'sum(np.amount) as amount', 'sum(np.total) as total')
            ->from('AppBundle:NoteProduct', 'np')
            ->innerJoin('np.note', 'n')
            ->innerJoin('np.product', 'p')
            ->innerJoin('n.user', 'u')
            ->innerJoin('p.category', 'c')
            ->where('n.status = \'Entregado\'')
            ->andWhere('n.checkout >= :tb')
            ->groupBy('n.user', 'c.id')
            ->orderBy('u.id');

        $dql->setParameter('tb', $t);

        return $dql->getQuery()->getResult();
    }

    public function findSalesByProductAndWaiter($t)
    {
        $em = $this->getEntityManager();
        $dql = $em->createQueryBuilder();
        $dql->select('concat(u.name, \' \', u.firstLastName) as waiter', 'p.name as product', 'sum(np.amount) as amount', 'sum(np.total) as total')
            ->from('AppBundle:NoteProduct', 'np')
            ->innerJoin('np.product', 'p')
            ->innerJoin('np.note', 'n')
            ->innerJoin('n.user', 'u')
            ->where('n.status = \'Entregado\'')
            ->andWhere('n.checkout >= :tb')
            ->groupBy('n.user', 'p.name')
            ->orderBy('u.id');

        $dql->setParameter('tb', $t);

        return $dql->getQuery()->getResult();
    }

    public function findSalesByAccountWaiter($t)
    {
        $em = $this->getEntityManager();
        $dql = $em->createQueryBuilder();
        $dql->select('concat(u.name, \' \', u.firstLastName) as waiter', 'a.id as account', 'a.checkin as acccheckin', 'a.checkout as acccheckout', 'n.numberNote', 'n.checkin', 'n.checkout', 'c.name as category', 'sum(np.amount) as amount', 'sum(np.total) as total')
            ->from('AppBundle:NoteProduct', 'np')
            ->innerJoin('np.product', 'p')
            ->innerJoin('p.category', 'c')
            ->innerJoin('np.note', 'n')
            ->innerJoin('n.account', 'a')
            ->innerJoin('a.user', 'u')
            ->where('n.status = \'Entregado\'')
            ->andWhere('n.checkout >= :tb')
            ->groupBy('a.id', 'n.id', 'p.category')
            ->orderBy('a.id');

        $dql->setParameter('tb', $t);

        return $dql->getQuery()->getResult();
    }

    public function findNoteProductId($accountId, $userId, $numberNote)
    {
        $em = $this->getEntityManager();
        $dql = $em->createQueryBuilder();
        $dql->select('n.id')
            ->from('AppBundle:NoteProduct', 'np')
            ->innerJoin('np.note', 'n')
            ->innerJoin('n.account', 'a')
            ->innerJoin('a.user', 'u')
            ->where('u.id = :userId')
            ->andWhere('n.numberNote = :folio')
            ->andWhere('n.status like \'%Pendiente%\'')
            ->andWhere('a.id = :accId')
            ->groupBy('n.id');

        $dql->setParameter('userId', $userId);
        $dql->setParameter('folio', $numberNote);
        $dql->setParameter('accId', $accountId);

        return $dql->getQuery()->getSingleResult();
    }
}
