<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * NoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NoteRepository extends EntityRepository
{
    public function findLastNoteIdByUser($user_id)
    {
        $tempNow = new \DateTime('now');

        $em = $this->getEntityManager();
        $dql = $em->createQueryBuilder();
        $dql->select('n.numberNote')
            ->from('AppBundle:Note', 'n')
            ->where('n.user = :userId')
            ->andWhere('n.checkin <= :tempNow')
            ->orderBy('n.checkin', 'DESC')
            ->setMaxResults(1);

        $dql->setParameter('tempNow', $tempNow);
        $dql->setParameter('userId', $user_id);

        return $dql->getQuery()->getResult();
    }

    public function findAllPendingNotes()
    {
        $tempNow = new \DateTime('now');

        $em = $this->getEntityManager();
        $dql = $em->createQueryBuilder();
        $dql->select('n.id', 'n.numberNote', 'n.checkin', 'n.status', 'concat(u.name, \' \', u.firstLastName) as mesero')
            ->from('AppBundle:Note', 'n')
            ->innerJoin('n.user', 'u')
            ->where('n.checkin <= :tempNow')
            ->setMaxResults(20);

        $dql->setParameter('tempNow', $tempNow);

        return $dql->getQuery()->getResult();
    }
}
