<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends EntityRepository
{
    public function findAllProducts()
    {
        $em = $this->getEntityManager();
        $dql = $em->createQueryBuilder();
        $dql->select('p.id', 'p.name', 'p.price', 'c.id as category')
            ->from('AppBundle:Product', 'p')
            ->join('p.category', 'c');

        return $dql->getQuery()->getResult();
    }

    public function findProductById($id)
    {
        $em = $this->getEntityManager();
        $dql = $em->createQueryBuilder();
        $dql->select('p.id', 'p.name', 'p.price')
            ->from('AppBundle:Product', 'p')
            ->where('p.id = :id');

        $dql->setParameter('id', $id);

        return $dql->getQuery()->getResult();
    }
}