easy_admin:
    site_name: 'Admin'
    formats:
      date: 'd/m/Y'
      time: 'H:i'
      datetime: 'F j, H:i:s'
    design:
      assets:
          favicon: 'img/republik.ico'
      color_scheme: 'dark'
      form_theme: 'horizontal'
      menu:
          - label: 'Ventas'
            icon: dollar
            children:
                - { entity: 'Account'}
                - { entity: 'Note'}
                - { entity: 'NoteProduct'}
          - label: 'Productos'
            icon: beer
            children:
                - { entity: 'Category' }
                - { entity: 'Product' }
          - entity: 'User'
            icon: user
    list:
        max_results: 20
        actions:
            - { name: 'show', label: '', icon: 'search'}
            - { name: 'edit', label: '', icon: 'pencil' }
            - { name: 'delete', label: '', icon: 'trash' }
            - { name: 'search', label: 'Búsqueda' }
    show:
        actions:
            - { name: 'edit', label: 'Actualizar' }
            - { name: 'list', label: 'Regresar al menú' }
    edit:
        actions:
            - { name: 'list', label: 'Regresar al menú' }
    new:
        actions:
            - { name: 'list', label: 'Regresar al menú' }
    entities:
        Account:
            label: 'Cuentas'
            class: AppBundle\Entity\Account
            disabled_actions: ['new', 'edit', 'delete', 'show']
            list:
                title: "Cuentas"
                fields:
                  - { property: 'id', label: 'Id' }
                  - { property: 'user', label: 'Mesero' }
                  - { property: 'checkin', label: 'Fecha de apertura' }
        Category:
            label: 'Categoría'
            class: AppBundle\Entity\Category
            list:
                actions:
                    - { name: 'new', label: 'Crear Categoría' }
                title: "Categorías"
                fields:
                  - { property: 'id', label: 'Id' }
                  - { property: 'name', label: 'Categoría' }
            show:
                title: "Categoría (#%%entity_id%%)"
                fields:
                  - { property: 'id', label: 'Id' }
                  - { property: 'name', label: 'Categoría' }
            new:
                title: "Crear Categoría"
                fields:
                  - { property: 'name', label: 'Categoría' }
            edit:
                title: "Modificar Categoría"
                fields:
                  - { property: 'name', label: 'Categoría' }
        Note:
            label: 'Comanda'
            class: AppBundle\Entity\Note
            disabled_actions: ['new', 'edit', 'delete', 'show']
            list:
                title: "Comandas"
                fields:
                  - { property: 'id', label: 'Id' }
                  - { property: 'user', label: 'Mesero' }
                  - { property: 'account', label: 'Cuenta' }
                  - { property: 'numberNote', label: 'Comanda' }
                  - { property: 'checkin', label: 'Fecha/Hora Emisión' }
                  - { property: 'checkout', label: 'Fecha/Hora Entrega' }
                  - { property: 'status', label: 'Status' }
                sort: ['checkin', 'DESC']
        NoteProduct:
            label: 'Detalles Comanda'
            class: AppBundle\Entity\NoteProduct
            disabled_actions: ['new', 'edit', 'delete', 'show']
            list:
                title: "Detalles Comanda"
                fields:
                  - { property: 'note', label: 'Comanda' }
                  - { property: 'product', label: 'Producto' }
                  - { property: 'amount', label: 'Cantidad' }
                  - { property: 'total', label: 'Total $' }
        Product:
            label: 'Productos'
            class: AppBundle\Entity\Product
            list:
                actions:
                  - { name: 'new', label: 'Crear Producto' }
                title: "Productos"
                fields:
                  - { property: 'id', label: 'Id' }
                  - { property: 'category', label: 'Categoría' }
                  - { property: 'name', label: 'Nombre' }
                  - { property: 'price', label: 'Precio $' }
                  - { property: 'stock', label: 'Stock' }
            show:
                title: "Producto (#%%entity_id%%)"
                fields:
                  - { property: 'id', label: 'Id' }
                  - { property: 'category', label: 'Categoría' }
                  - { property: 'name', label: 'Nombre' }
                  - { property: 'price', label: 'Precio $' }
                  - { property: 'stock', label: 'Stock' }
            new:
                title: "Crear Producto"
                fields:
                  - { property: 'name', label: 'Nombre' }
                  - { property: 'category', label: 'Categoría' }
                  - { property: 'price', label: 'Precio $' }
                  - { property: 'stock', label: 'Stock' }
            edit:
                title: "Modificar Producto"
                fields:
                  - { property: 'name', label: 'Nombre' }
                  - { property: 'category', label: 'Categoría' }
                  - { property: 'price', label: 'Precio $' }
                  - { property: 'stock', label: 'Stock' }
        User:
            label: 'Usuarios'
            class: AppBundle\Entity\User
            list:
                actions:
                    - { name: 'new', label: 'Crear Usuario' }
                title: 'Usuarios'
                fields:
                    - { property: 'id', label: 'Id' }
                    - { property: 'name', label: 'Nombre' }
                    - { property: 'firstLastName', label: 'Apellido Paterno' }
                    - { property: 'secondLastName', label: 'Apellido Materno' }
                    - { property: 'username', label: 'Usuario' }
                    - { property: 'cellphoneNumber', type: 'text', label: 'Celular' }
                    - { property: 'roles' }
                    - { property: 'enabled', label: 'Activo' }
            show:
                title: "Usuario (#%%entity_id%%)"
                fields:
                    - { property: 'name', label: 'Nombre' }
                    - { property: 'firstLastName', label: 'Apellido Paterno' }
                    - { property: 'secondLastName', label: 'Apellido Materno' }
                    - { property: 'username', label: 'Usuario' }
                    - { property: 'email', label: 'Correo electrónico' }
                    - { property: 'cellphoneNumber', type: 'text', label: 'Celular' }
                    - { property: 'enabled', label: 'Activo' }
            edit:
                title: "Modificar Usuario"
                fields:
                    - { property: 'name', label: 'Nombre' }
                    - { property: 'firstLastName', label: 'Apellido Paterno' }
                    - { property: 'secondLastName', label: 'Apellido Materno' }
                    - { property: 'email', label: 'Correo electrónico' }
                    - { property: 'cellphoneNumber', type: 'text', label: 'Celular' }
                    - { property: 'enabled', type: 'checkbox', label: 'Activo' }
                    - { property: 'username', label: 'Usuario' }
                    - { property: 'plainPassword', type: 'text', type_options: { required: false }, label: 'Contraseña' }
                    - { property: 'roles', type: 'choice', type_options: { multiple: true, expanded: false, choices: { ROLE_CAJERO: 'Cajero', ROLE_PALOMA: 'Paloma', ROLE_PALOMASHOTS: 'Paloma Shots', ROLE_MESERO: 'Mesero', ROLE_ADMIN: 'Administrador' } } }
                form_options: { validation_groups: ['Profile'] }
            new:
                title: "Crear Usuario"
                fields:
                    - { property: 'name', label: 'Nombre' }
                    - { property: 'firstLastName', label: 'Apellido Paterno' }
                    - { property: 'secondLastName', label: 'Apellido Materno' }
                    - { property: 'email', label: 'Correo electrónico' }
                    - { property: 'cellphoneNumber', type: 'text', label: 'Celular' }
                    - { property: 'enabled', type: 'checkbox', label: 'Activo' }
                    - { property: 'username', label: 'Usuario' }
                    - { property: 'plainPassword', type: 'text', type_options: { required: true}, label: 'Contraseña' }
                    - { property: 'roles', type: 'choice', type_options: { multiple: true, expanded: false, choices: { ROLE_CAJERO: 'Cajero', ROLE_PALOMA: 'Paloma', ROLE_PALOMASHOTS: 'Paloma Shots', ROLE_MESERO: 'Mesero', ROLE_ADMIN: 'Administrador' } } }
                form_options: { validation_groups: ['Registration'] }