# app/config/security.yml
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_CAJERO:        ROLE_CAJERO
        ROLE_PALOMASHOTS:   ROLE_PALOMASHOTS
        ROLE_PALOMA:        ROLE_PALOMA
        ROLE_MESERO:        ROLE_MESERO
        ROLE_ADMIN:         ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                login_path: /login
                check_path: /login_check
                csrf_token_generator: security.csrf.token_manager
                remember_me: true
                default_target_path: /
            logout:
                path:   /logout
                target: /login
                invalidate_session: true
            anonymous: true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/corte/*, role: ROLE_CAJERO }
        - { path: ^/pendientes/*, role: ROLE_PALOMA }
        - { path: ^/cuentas/*, role: [ROLE_MESERO, ROLE_PALOMASHOTS] }
        - { path: ^/comandas/*, role: [ROLE_MESERO, ROLE_PALOMASHOTS] }
        - { path: ^/api/*, role: [ROLE_ADMIN, ROLE_MESERO, ROLE_PALOMA, ROLE_PALOMASHOTS] }
        - { path: ^/cancelaciones/*, role: ROLE_ADMIN }
        - { path: ^/admin, role: ROLE_ADMIN }
